<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
$html = '';
$id = $block->getIdModifier() ? '-' . $block->getIdModifier() : time();
?>
<div class="col-12 col-md-10 offset-md-1 d-flex justify-content-end align-items-center">
    <div class="dropdown">
        <button class="btn dropdown-toggle account" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
        </button>
        <div class="dropdown-menu account-item show" aria-labelledby="dropdownMenuButton">
            <div class="row no-gutters dropdown-content">

                <?php
                foreach ($this->getLinks() as $link) {
                    $html .= '<div class="col-6">
                  <div class="link link-account">
                    <div class="link-hover">
                      <div class="icon-round d-flex justify-content-center align-items-center">
                        <i class="fa fa-user" aria-hidden="true"></i>
                      </div>'
                        .$this->renderLink($link)
                        .'</div>
                  </div>
                </div>';
                }
                echo $html;
                ?>
            </div>
        </div>
    </div>
</div>





