<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
    <div class="button-wrap">
        <form>
            <div class="form-row align-items-center">
                <?php if ($block->shouldRenderQuantity()): ?>
                    <div class="col-auto qty">
                        <label for="qty"><?= /* @escapeNotVerified */ __('Qty') ?></label>
                        <input type="number"
                               class="form-control"
                               id="qty"
                               name="qty"
                               value="<?= /* @escapeNotVerified */ $block->getProductDefaultQty() * 1 ?>"
                               title="<?= /* @escapeNotVerified */ __('Qty') ?>"
                               data-validate="<?= $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>">
                    </div>
                <?php endif; ?>

                <div class="col-auto">
                    <button type="submit"
                            class="btn btn-dark custom-btn"
                            title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                            id="product-addtocart-button">
                            <?= /* @escapeNotVerified */ $buttonTitle ?>
                    </button>
                    <?= $block->getChildHtml('', true) ?>
                </div>
            </div>
        </form>
    </div>
<?php endif; ?>
<?php if ($block->isRedirectToCartEnabled()) : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/product/view/validation": {
                "radioCheckboxClosest": ".nested"
            }
        }
    }
</script>
<?php else : ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>
<?php endif; ?>
