<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php if ($crumbs && is_array($crumbs)) : ?>
<div class="col-lg-6">
    <div class="d-flex justify-content-start">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb sub-menu-list">
                <?php foreach ($crumbs as $crumbName => $crumbInfo) : ?>
                    <?php if ($crumbInfo['link']) : ?>
                        <li class="breadcrumb-item">
                            <a href="<?= /* @escapeNotVerified */ $crumbInfo['link'] ?>"><?= $block->escapeHtml($crumbInfo['label']) ?></a>
                        </li>
                    <?php elseif ($crumbInfo['last']) : ?>
                        <li class="breadcrumb-item active">
                            <?= $block->escapeHtml($crumbInfo['label']) ?>
                        </li>
                    <?php endif; ?>
                <?php endforeach; ?>
            </ol>
        </nav>
    </div>
</div>
<?php endif; ?>
