<div class="row">
    <a class="navbar-brand mx-auto" href="#"><img src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/logo.png" alt=""></a>
</div>
<div class="row">
    <div class="footer-nav">
        <ul>
            <li><a href="#">Über uns</a></li>
            <li><a href="#">Kontakt</a></li>
            <li><a href="#">Datenschutzbestimmungen</a></li>
            <li><a href="#">Versandkosten und Lieferung </a></li>
            <li><a href="#">Widerrufsbelehrung</a></li>
            <li><a href="#">Impressum</a></li>
        </ul>
    </div>
</div>