<div class="row sign-in">
    <div class="col-12 col-md-10 offset-md-1 d-flex justify-content-end align-items-center">
        <?php echo $this->getChildHtml("authorization_link"); ?>
        <p>or</p>
        <?php echo $this->getChildHtml("sign_link"); ?>
        <div class="dropdown">
            <button class="btn dropdown-toggle account" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
            </button>
            <div class="dropdown-menu account-item show" aria-labelledby="dropdownMenuButton">
                <div class="row no-gutters dropdown-content">
                    <div class="col-6">
                        <div class="link link-account">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                </div>
                                <a href="http://magento.loc/customer/account/">Mein Konto</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="link link-order">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-address-book" aria-hidden="true"></i>
                                </div>
                                <a href="http://192.168.2.119/sales/order/history/">Bestellunge</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="link link-wishlist">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-star" aria-hidden="true"></i>
                                </div>
                                <a href="http://192.168.2.119/wishlist/">Merkzettel</a>
                            </div></div>
                    </div>
                    <div class="col-6">
                        <div class="link link-logout">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-download" aria-hidden="true"></i>
                                </div>
                                <a href="http://192.168.2.119/customer/account/logout/">Abmelden</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>
<div class="row custom-nav">
    <div class="col-12 col-md-10 offset-md-1">
        <nav class="navbar navbar-expand-lg d-lg-flex align-items-lg-end">
			<?php echo $this->getChildHtml("logo"); ?>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
                <span class="navbar-toggler-icon"></span>
            </button>
			<?php echo $this->getChildHtml('catalog.topnav'); ?>
		</nav>
	</div>
</div>
<div class="row search">
    <?php echo $this->getChildHtml("topSearch"); ?>
</div>



