<style>
    .container-fluid {
        width: 80%;
        margin: 50px auto;
    }
    .container-fluid img.slide-item {
        width: 100%;
    }
</style>
<div class="container-fluid">
    <div class="bannre-main">
        <div class="d-none d-md-block col-md-6">
            <img class="slide-item" src="/static/version1530347833/frontend/Safta/sample/en_US/images/banner-man.png" alt="man">
        </div>
        <div class="col-6 col-md-3 d-flex align-items-center justify-content-center">
            <div class="seasons d-flex flex-column align-items-center justify-content-center">
                <a class="d-block diagonal season" href="#">
                    <h2>Autumn</h2>
                    <h2>/</h2>
                    <h2>Winter</h2>
                </a>
                <a class="video d-block" href="#">
                    <img src="/static/version1530347833/frontend/Safta/sample/en_US/images/video-ico.png" alt="">
                    <span>video</span>
                </a>
            </div>
        </div>
        <a class="carousel-control-prev custom-control" href="#banner-sl" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next custom-control" href="#banner-sl" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
