<style>
    .collections {
        background-image: url(/static/version1530347833/frontend/Safta/sample/en_US/images/collestion-man.png), url(/static/version1530347833/frontend/Safta/sample/en_US/images/collestion-woman.png);
        background-repeat: no-repeat, no-repeat;
        background-position: 0% 0%, 100% 0%;
        -webkit-background-size: 59%, 76%;
        -moz-background-size: 59%, 76%;
        -o-background-size: 59%, 76%;
        background-size: 59%, 76%;
        padding: 5vw 0;
        margin-top: 4vw;
    }
    .collections .wrapper {
        max-width: 83.333333%;
        flex: 0 0 83.333333%;
        margin: 0 auto;
        display: flex;
    }
    .collections .height {
        height: 26vw;
    }
    .collections .wrapper .man-colect {
        justify-content: flex-end;
        flex: 0 0 41.666667%;
        max-width: 41.666667%;
    }
    .collections .women-colect {
        display: -webkit-flex;
        display: -ms-flex;
        display: flex;
        align-items: flex-end;
    }
    .man-colect, .women-colect {
        display: -webkit-flex;
        display: -ms-flex;
        display: flex;
        flex: 0 0 58.333333%;
        max-width: 58.333333%;
        padding: 0 15px;
    }
</style>
<section class="collections">
    <div class="wrapper">
        <div class="height man-colect">
            <h1>For</h1>
            <h2>/</h2>
            <h2>Man</h2>
        </div>
        <div class="height women-colect">
            <h1>For</h1>
            <h2>/</h2>
            <h2>Woman</h2>
        </div>
    </div>
</section>