<div class="connect-capt">
    <h2>Connect with us</h2>
</div>
<div class="wrapper">
    <div class="connekct-item frst">
        <a href="https://www.facebook.com/verypoolish/" class="round">
            <i class="fa fa-facebook" aria-hidden="true"></i>
        </a>
        <p>Like us on Facebook</p>
    </div>
    <div class="connekct-item">
        <a href="https://www.instagram.com/superlegere/" class="round">
            <i class="fa fa-instagram" aria-hidden="true"></i>
        </a>
        <p>Follow us on Instagram</p>
    </div>
</div>
