<div class="footer-capt">
    <a class="foot-navbar-brand" href="#"><img src="/static/version1530347833/frontend/Safta/sample/en_US/images/logo.png" alt=""></a>
</div>
<div class="footer-nav">
    <ul>
        <li><a href="http://superlegere.loc/about-us/">POOL</a></li>
        <li><a href="http://superlegere.loc/impressum/">Impressum</a></li>
        <li><a href="http://superlegere.loc/agb/">AGB</a></li>
        <li><a href="http://superlegere.loc/datenschutz/">Datenschutz</a></li>
        <li><a href="http://superlegere.loc/jobs/">Jobs</a></li>
        <li>&nbsp;</li>
        <li class="last">&nbsp;</li>
    </ul>
</div>
<div class="coperight">
    <p>© 2018. all rights reserved.</p>
</div>

