<section class="instagram">
    <div class="insta-capt"><img alt="" src="/static/version1530347833/frontend/Safta/sample/en_US/images/instagram.png"></div>
    <div class="wrapper">
        <div class="nesting-1 col-left">
            <div class="nesting-2"><a class="inst" href="#"><img alt="" src="/static/version1530347833/frontend/Safta/sample/en_US/images/inst1.jpg"></a></div>
            <div class="nesting-2"><a class="inst" href="#"><img alt="" src="/static/version1530347833/frontend/Safta/sample/en_US/images/inst2.jpg"></a></div>
        </div>
        <div class="nesting-1 col-right">
            <div class="nesting-2 row-top"><a class="inst" href="#"><img alt="" src="/static/version1530347833/frontend/Safta/sample/en_US/images/inst3.jpg"></a></div>
            <div class="nesting-2 row-bottom">
                <div class="nesting-3"><a class="inst" href="#"><img alt="" src="/static/version1530347833/frontend/Safta/sample/en_US/images/inst4.jpg"></a></div>
                <div class="nesting-3"><a class="inst" href="#"><img alt="" src="/static/version1530347833/frontend/Safta/sample/en_US/images/inst5.jpg"></a></div>
            </div>
        </div>
    </div>
</section>