<?php
$categories = $block->getCategoryCollection()->toArray();


//echo '<pre>';
//print_r($categories);
//echo '<pre>';

unset($categories[2]);



foreach ($categories as &$cat)
    $cat['children'] = array();


foreach ($categories as $key=>$item) {
    if($item['include_in_menu'] == 0) {
        unset($categories[$key]);
    }
}

foreach ($categories as $id => &$cat)
{
    if ($cat['parent_id'] != 2)
        $categories[$cat['parent_id']]['children'][$id] = &$cat;
}

// Remove children from $menuItems so only top level items remain
foreach (array_keys($categories) as $id)
{
    if ($categories[$id]['parent_id'] != 2)
        unset($categories[$id]);
}

echo '<pre>';
print_r($categories);
echo '<pre>';



//$html = '';
//foreach ($arr as $key=> $value){
//    if(!$value == null){
//        $html .= '<li>'.$categories[$key]["name"].'</li><ul>';
//        foreach ($value as $sub_key => $sub_value) {
//            if (!$sub_value == null) {
//                $html .= '<li>'.$categories[$sub_key]['name'].'</li><ul>';
//                foreach ($sub_value as $sub_sub_key=>$sub_sub_value){
//                    if(!$sub_sub_value == null) {
//                        $html .= '<li>'.$categories[$sub_sub_key]['name'].'</li><ul>';
//                        foreach ($sub_sub_value as $sss_key=>$sss_value) {
//                            echo '+++';
//                        }
//                        $html .= '</ul>';
//                    } else {
//                        $html .= '<li>'.$categories[$sub_sub_key]['name'].'</li>';
//                    }
//                }
//                $html .= '</ul>';
//            } else {
//                $html .= '<li>'.$categories[$sub_key]['name'].'</li>';
//            }
//        }
//        $html .= '</ul>';
//    } else {
//        $html .= '<li>'.$categories[$key]["name"].'</li>';
//    }
//}
//$html .= '</ul>';
//echo $html;



$menuItems = array
(
    1 => array(
        'ItemText' => 'Home',
        'ItemLink' => 'index.php',
        'ParentID' => null,
    ),

    2 => array(
        'ItemText' => 'Home Sub 1',
        'ItemLink' => 'somepage.php',
        'ParentID' => 1,
    ),

    3 => array(
        'ItemText' => 'Home Sub 2',
        'ItemLink' => 'somepage2.php',
        'ParentID' => 1,
    ),

    4 => array(
        'ItemText' => 'Contact',
        'ItemLink' => 'contact.php',
        'ParentID' => null,
    ),
);

// Each node starts with 0 children
foreach ($menuItems as &$menuItem)
    $menuItem['Children'] = array();

// If menu item has ParentID, add it to parent Children array
foreach ($menuItems as $ID => &$menuItem)
{
    if ($menuItem['ParentID'] != null)
        $menuItems[$menuItem['ParentID']]['Children'][$ID] = &$menuItem;
}

// Remove children from $menuItems so only top level items remain
foreach (array_keys($menuItems) as $ID)
{
    if ($menuItems[$ID]['ParentID'] != null)
        unset($menuItems[$ID]);
}

//echo '<pre>';
//print_r($menuItems);
//echo '<pre>';
?>

