<div class="container-fluid">
    <div class="bannre-main">
        <div class="row banner-bg">
            <div id="banner-sl" class="carousel slide" data-ride="carousel">
                <div class="row indicators-sl">
                    <div class="col-6 col-md-3">
                        <ol class="carousel-indicators d-none d-md-flex justify-content-start">
                            <li data-target="#banner-sl" data-slide-to="0" class="active"><span class="color-indicator"></span>1</li>
                            <li data-target="#banner-sl" data-slide-to="1"><span class="color-indicator"></span>2</li>
                            <li data-target="#banner-sl" data-slide-to="2"><span class="color-indicator"></span>3</li>
                        </ol>
                    </div>
                </div>
                <div class="carousel-inner">
                    <div class="carousel-item active">
                        <div class="row">
                            <div class="col-12 offset-0 col-md-10 offset-md-1">
                                <div class="row d-flex align-items-center">
                                    <div class="col-6 col-md-3 d-flex align-items-center justify-content-center">
                                        <div class="diagonal year float-right">
                                            <p>01</p>
                                            <p>17</p>
                                            <div class="background"><a href="#"></a></div>
                                        </div>
                                    </div>
                                    <div class="d-none d-md-block col-md-6">
                                        <img class="slide-item" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/banner-man.png" alt="man">
                                    </div>
                                    <div class="col-6 col-md-3 d-flex align-items-center justify-content-center">
                                        <div class="seasons d-flex flex-column align-items-center justify-content-center">
                                            <a class="d-block diagonal season" href="#">
                                                <h2>Autumn</h2>
                                                <h2>/</h2>
                                                <h2>Winter</h2>
                                            </a>
                                            <a class="video d-block" href="#">
                                                <img src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/video-ico.png" alt="">
                                                <span>video</span>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev custom-control" href="#banner-sl" role="button" data-slide="prev">
                    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next custom-control" href="#banner-sl" role="button" data-slide="next">
                    <span class="carousel-control-next-icon" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </div>
</div>