<div class="container-fluid">
    <div class="row">
        <div class="col-5 d-flex justify-content-end height">
            <a class="diagonal man d-block" href="#">
                <h1>For</h1>
                <h2>/</h2>
                <h2>Man</h2>
            </a>
        </div>
        <div class="col-7 d-flex align-items-end height">
            <a class="diagonal woman d-block" href="#">
                <h1>For</h1>
                <h2>/</h2>
                <h2>Woman</h2>
            </a>
        </div>
    </div>
</div>
