<section class="connect">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 col-md-10 offset-md-1 col-lg-8 offset-lg-2">
                <div class="row connect-capt d-flex justify-content-center">
                    <h2>Connect with us</h2>
                </div>
                <div class="row no-gutters">
                    <div class="col-6 col-md-3 d-flex flex-column align-items-center connekct-item">
                        <a href="#" class="round d-flex justify-content-center align-items-center">
                            <i class="fa fa-facebook" aria-hidden="true"></i>
                        </a>
                        <p>Like us on Facebook</p>
                    </div>
                    <div class="col-6 col-md-3 d-flex flex-column align-items-center connekct-item">
                        <a href="#" class="round d-flex justify-content-center align-items-center">
                            <i class="fa fa-twitter" aria-hidden="true"></i>
                        </a>
                        <p>Follow us on Twitter</p>
                    </div>
                    <div class="col-6 col-md-3 d-flex flex-column align-items-center connekct-item">
                        <a href="#" class="round d-flex justify-content-center align-items-center">
                            <i class="fa fa-pinterest-p" aria-hidden="true"></i>
                        </a>
                        <p>See us on Pinterest</p>
                    </div>
                    <div class="col-6 col-md-3 d-flex flex-column align-items-center connekct-item">
                        <a href="#" class="round d-flex justify-content-center align-items-center">
                            <i class="fa fa-google-plus" aria-hidden="true"></i>
                        </a>
                        <p>Follow us on Google</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>