<section class="instagram">
    <div class="container-fluid">
        <div class="row insta-capt">
            <img class="mx-auto" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/instagram.png" alt="">
        </div>
        <div class="row no-gutters">
            <div class="col-lg-6">
                <div class="row no-gutters">
                    <div class="col-sm-6">
                        <a class="inst" href="#"><img class="w-100 d-block" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/inst1.jpg" alt=""></a>
                    </div>
                    <div class="col-sm-6">
                        <a class="inst" href="#"><img class="w-100 d-block" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/inst2.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="row no-gutters">
                    <div class="col-12">
                        <a class="inst" href="#"><img class="w-100 d-block" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/inst3.jpg" alt=""></a>
                    </div>
                    <div class="col-sm-6">
                        <a class="inst" href="#"><img class="w-100 d-block" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/inst4.jpg" alt=""></a>
                    </div>
                    <div class="col-sm-6">
                        <a class="inst" href="#"><img class="w-100 d-block" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/inst5.jpg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>