<div class="container-fluid">
    <div class="row">
        <div class="col-4 col-sm-3 col-md-2 offset-md-1">
            <img class="w-100" src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/shtamp.png" alt="">
        </div>
        <div class="col-8 col-sm-4 col-md-3">
            <h2 class="newsl">Newsletter!</h2>
        </div>
        <div class="col-12 col-sm-5 col-md-4">
            <form class="forml">
                <div class="form-group">
                    <input type="email" class="form-control" id="email-lrtter" aria-describedby="emailHelp" placeholder="Your email">
                </div>
                <button type="submit" class="btn float-right"><img src="http://magento.loc/static/version1530347833/frontend/Safta/sample/en_US/images/ok.png" alt=""></button>
            </form>
        </div>
    </div>
</div>
