<section class="single-prod">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                <div class="row shop-main">
                    <div class="col-12">
                        <div class="row no-gutters single-card">
                            <div class="col-md-6 col-xl-8">
                                <div class="card-body">
                                    <div class="row common-info">
                                        <div class="col card-inform">
                                            <div class="capt-info d-flex justify-content-between">
                                                <?php echo $this->getChildHtml("prod_title"); ?>
                                                <?php echo $this->getChildHtml("product.price.final"); ?>
                                            </div>
                                            <?php echo $this->getChildHtml("product.info.type"); ?>
                                        </div>
                                    </div>
                                    <div class="row details">
                                        <div class="col card-details">
                                            <?php echo $this->getChildHtml("adtocard"); ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>