<div class="row sign-in">
    <div class="col-12 col-md-10 offset-md-1 d-flex justify-content-end align-items-center">

        <div class="form-group header-select">
            <select onchange="location.href=this.value" class="form-control lang" id="Select1">
                <option value="#">Deutsch</option>
                <option value="http://verypoolish.itservices.in.ua/?SID=npduo4scg81itlgo5qoprpudsd&amp;___store=default&amp;___from_store=en">English</option>
            </select>
        </div>
        <div class="header-select">
            <select onchange="location.href=this.value" class="form-control lang" id="Select2">
                <option value="http://192.168.2.119/customaction/currency/set/currency/EUR/">EUR</option>
                <option value="http://192.168.2.119/customaction/currency/set/currency/GBP/">GBP</option>
                <option value="http://192.168.2.119/customaction/currency/set/currency/JPY/">JPY</option>
                <option value="http://192.168.2.119/customaction/currency/set/currency/CHF/">CHF</option>
                <option value="http://192.168.2.119/customaction/currency/set/currency/USD/">USD</option>
            </select>
        </div>

        <button type="button" class="btn" data-toggle="modal" data-target="#login" data-whatever="@mdo">Anmelden</button>
        <p>or</p>
        <button type="button" class="btn" data-toggle="modal" data-target="#register" data-whatever="@fat">Registrieren</button>

        <div class="dropdown">
            <button class="btn dropdown-toggle account" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Account
            </button>
            <div class="dropdown-menu account-item show" aria-labelledby="dropdownMenuButton">
                <div class="row no-gutters dropdown-content">
                    <div class="col-6">
                        <div class="link link-account">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-user" aria-hidden="true"></i>
                                </div>
                                <a href="http://192.168.2.119/customer/account/">Mein Konto</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="link link-order">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-address-book" aria-hidden="true"></i>
                                </div>
                                <a href="http://192.168.2.119/sales/order/history/">Bestellunge</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-6">
                        <div class="link link-wishlist">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-star" aria-hidden="true"></i>
                                </div>
                                <a href="http://192.168.2.119/wishlist/">Merkzettel</a>
                            </div></div>
                    </div>
                    <div class="col-6">
                        <div class="link link-logout">
                            <div class="link-hover">
                                <div class="icon-round d-flex justify-content-center align-items-center">
                                    <i class="fa fa-download" aria-hidden="true"></i>
                                </div>
                                <a href="http://192.168.2.119/customer/account/logout/">Abmelden</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>