<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())): ?>
<?php
    $type = 'widget-product-grid';

    $mode = 'grid';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::DEFAULT_VIEW;
    $description = false;
?>
<section class="category-prod">
    <div class="container-fluid">
        <div class="row">
            <div class="col-xl-10 offset-xl-1">
                <div class="row">
                    <?php $iterator = 1; ?>
                    <?php foreach ($items as $_item): ?>
                        <div class="col-md-3 interior">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product card">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                                <div class="card-body">
                                    <h3 class="card-title">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </h3>
                                </div>
                            </a>
                        </div>
                    <?php endforeach ?>
                </div>
            </div>
            <?= $block->getPagerHtml() ?>
        </div>
    </div>
</section>
<?php endif;?>
