<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<section class="newsletter">
    <div class="wrapper">
        <div class="shtamp"><img class="with-100" alt=""
                                 src="/static/version1530347833/frontend/Safta/sample/en_US/images/shtamp.png"></div>
        <div class="letter">
            <h2 class="newsl">Newsletter!</h2>
        </div>
        <div class="letter-form">
            <form class="forml"
                  novalidate
                  action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                  method="post"
                  data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                  id="newsletter-validate-detail">
                <div class="nl-form-group"><input id="email-lrtter" class="nl-form-control" type="email"
                                                  placeholder="Your email"></div>
                <button class="nl-btn" type="submit"><img alt=""
                                                          src="/static/version1530347833/frontend/Safta/sample/en_US/images/ok.png">
                </button>
            </form>
        </div>
    </div>
</section>
