<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

            <form class="form form-login"
                  action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                  method="post"
                  id="login-form"
                  data-mage-init='{"validation":{}}'>
                <?= $block->getBlockHtml('formkey') ?>
                <div class="modal-header">
                    <h3>Please sign in</h3>
                </div>


                <div class="modal-body">
                    <label for="email" class="sr-only"><?= $block->escapeHtml(__('Email adress')) ?></label>
                    <input type="email" name="login[username]"
                           id="email"
                           value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                        <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                           class="form-control"
                           data-validate="{required:true, 'validate-email':true}">

                    <label for="pass" class="sr-only">Password</label>
                    <input type="password"
                           id="pass"
                           class="form-control"
                           name="login[password]"
                           placeholder="Password"
                        <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                           data-validate="{required:true}"
                           required>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>

                <div class="modal-footer">
                    <button class="btn btn-lg btn-block"
                            type="submit"
                            name="send"
                            id="send2">
                        Anmelden
                    </button>
                </div>

            </form>

    </div>
</div>
