<?php
/**
 * Copyright © 2011-2018 Karliuka Vitalii(karliuka.vitalii@gmail.com)
 *
 * See COPYING.txt for license details.
 */
?>
<?php
$class = $block->getType();
$image = 'most_viewed_products_list';
$items = $block->getItems();
$showAddTo = true;
$showCart  = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<?php if ($block->getItems()->getSize()): ?>
    <div class="block <?php /* @escapeNotVerified */ echo $class ?>">
        <div class="block-title title">
            <h1 class="header-slider"><?php /* @escapeNotVerified */ echo $block->getTitle() ?></h1>
        </div>
        <div class="block-content content" aria-labelledby="block-<?php /* @escapeNotVerified */ echo $class ?>-heading">
            <div class="products wrapper grid products-grid products-<?php /* @escapeNotVerified */ echo $class ?>">
                <ol class="products list items product-items">
                    <?php $iterator = 1 ?>

                    <?php foreach ($items as $_item): ?>
                        <div class="pr-slide">
                            <a class="pr-card product" href="<?php /* @escapeNotVerified */ echo $block->getProductUrl($_item) ?>" tabindex="0">
                                <?php echo $block->getImage($_item, $image)->toHtml() ?>
                                <div class="pr-card-body">
                                    <div class="pr-head">
                                        <h3 class="pr-card-title"><?php echo $block->escapeHtml($_item->getName()) ?></h3>
                                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
                                    </div>
                                </div>
                            </a>
                        </div>

                    <?php endforeach ?>

                </ol>
            </div>
        </div>
    </div>
<?php endif ?>